/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVotingVaultView,
  IVotingVaultViewInterface,
} from "../../../../contracts/snapshot/BalanceQuery.sol/IVotingVaultView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "queryVotePowerView",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVotingVaultView__factory {
  static readonly abi = _abi;
  static createInterface(): IVotingVaultViewInterface {
    return new utils.Interface(_abi) as IVotingVaultViewInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVotingVaultView {
    return new Contract(address, _abi, signerOrProvider) as IVotingVaultView;
  }
}
