/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BalanceQuery } from "./BalanceQuery";
export type { IVotingVaultView } from "./IVotingVaultView";
