/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirdropSeason0 } from "./AirdropSeason0";
export type { AirdropSeason1 } from "./AirdropSeason1";
export type { AirdropSeason1L2 } from "./AirdropSeason1L2";
export type { ArcadeAirdropBase } from "./ArcadeAirdropBase";
