/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdrop from "./airdrop";
export type { airdrop };
export type { ArcadeToken } from "./ArcadeToken";
export type { ArcadeTokenDistributor } from "./ArcadeTokenDistributor";
